[package]
name = "boot-dat-gen"
version = "0.2.1"
edition = "2021"
description = "command line to generate a boot.dat from a payload for the switch"
repository = "https://github.com/marcograss/boot-dat-gen"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.65"
clap = "3.2.22"
tx-custom-boot = "0.3.0"
